blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.vectored.dev/apistudio/
    about: Read the full API Studio documentation
  - name: Support Us
    url: https://ko-fi.com/openpost
    about: Buy us a coffee on Ko-fi
